---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Курс "R, визуализация и статистика"

### Установка R и RStudio.
[R](https://www.r-project.org/), [RStudio](https://www.rstudio.com/products/rstudio/download/#download), [Rstudio cloud](https://rstudio.cloud), [RStudio online on rollapp](https://www.rollapp.com/app/rstudio), [R-bloggers](https://www.r-bloggers.com/)

### Занятие 1. Введение в R и RStudio. Вектор. Датафрем. Установка и работа с пакетами.

* [материалы занятия](https://agricolamz.github.io/2019_FE_R_statistics/Lab_1.html)
* [домашнее задание](https://docs.google.com/forms/d/e/1FAIpQLScLWNxqwls7ZDxB7S4OyhOWM3U86g-PSwxYfNpSWHqme5KiQQ/viewform?c=0&w=1)

### Занятие 2. Пользовательские функции. Пакет `tidyverse`.

* [материалы занятия](https://agricolamz.github.io/2019_FE_R_statistics/Lab_2.html)
* [домашнее задание](https://docs.google.com/forms/d/e/1FAIpQLSd4R-RgfVA8RJm0DqMZZhuH-T3uuHpiqb0H-F8yyyKB7zJihg/viewform?c=0&w=1)

### Занятие 3-4. Визуализация. Пакет `ggplot2`, `rmarkdown`. `plotly`. `shiny`.
* [материалы занятия 3](https://agricolamz.github.io/2019_FE_R_statistics/Lab_3.html)
* [материалы занятия 4](https://agricolamz.github.io/2019_FE_R_statistics/Lab_4.html)
* [домашнее задание](https://docs.google.com/forms/d/e/1FAIpQLSc2Z6snhSEZRVzHysYsUdKFkl4flE63AY4TFd-UrkmstV8s4g/viewform)

### Занятия 5. Описантельная статистика. Введение в байесовскую статистику
* [материалы занятия 5](https://agricolamz.github.io/2019_FE_R_statistics/Lab_5.html)

### Занятие 6. Функция правдоподобия, формула Байеса

* [материалы занятия 6](https://agricolamz.github.io/2019_FE_R_statistics/Lab_6.html)

### Занятие 7. Биномиальные данные
* [материалы занятия](https://agricolamz.github.io/2019_FE_R_statistics/Lab_7.html)

### Занятие 8. Доверительные интервалы. Биномиальный тест
* [материалы занятия](https://agricolamz.github.io/2019_FE_R_statistics/Lab_8.html)

### Занятие 9. Байесовский фактор 
* [материалы занятия](https://agricolamz.github.io/2019_FE_R_statistics/Lab_9.html)

### Занятие 10. Надо придумать про что
* [материалы занятия](https://agricolamz.github.io/2019_FE_R_statistics/Lab_10.html)

Календарь можно скачать [в формате `.csv`](https://raw.githubusercontent.com/agricolamz/2019_FE_R_statistics/master/timetable.csv) и импортировать в Google Calendar, MS Outlook и т. п.

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(timevis)
df <- read_csv("timetable.csv")
df %>% 
  mutate(`Start Date` = dmy(`Start Date`),
         id = 1:n(),
         Subject = paste0(
           "<a href = 'https://agricolamz.github.io/2019_FE_R_statistics/",
           gsub(" ", "_",Subject),
           ".html'>",
           Subject,
           "</a> <br>",
           wday(`Start Date`, label = TRUE),
           " ",
           day(`Start Date`),
           ".",
           month(`Start Date`))
         ) %>% 
  select("start" = "Start Date", "content" = "Subject") %>% 
  timevis()
```